export const DATA_ASSET_KEYS = Object.freeze({
    DUNGEON_THEMES: 'DUNGEON_THEMES',
    ENEMIES: 'ENEMIES',
    CHARACTERS: 'CHARACTERS',
    ITEMS: 'ITEMS',
});

export const DUNGEON_ASSET_KEYS = Object.freeze({
    WORLD: 'WORLD',
    UNITS: 'UNITS',
    ITEMS: 'ITEMS',
    EFFECTS_LARGE: 'EFFECTS_LARGE',
    EFFECTS_SMALL: 'EFFECTS_SMALL',
    TILE_STATUS: 'TILE_STATUS',
    HORIZONTAL_BARS: 'HORIZONTAL_BARS',
});

export const UI_ASSET_KEYS = Object.freeze({
    HORIZONTAL_BARS: 'HORIZONTAL_BARS',
    PANEL: 'PANEL',
    BUTTON_SKILLS: 'BUTTON_SKILLS',
});

